const vehicleModel = [
    {
        id:"1",
        vehicleModel:"Volkswagen"
    },
    {
        id:"2",
        vehicleModel:"VolBMWkswagen"
    },
    {
        id:"3",
        vehicleModel:"Audi"
    },
    {
        id:"4",
        vehicleModel:"Ford"
    },
    {
        id:"5",
        vehicleModel:"Opel"
    },
    {
        id:"6",
        vehicleModel:"Toyota"
    },
    {
        id:"7",
        vehicleModel:"Renault"
    },
    {
        id:"8",
        vehicleModel:"Skoda"
    },
    {
        id:"9",
        vehicleModel:"Peugeot"
    },
]

export default vehicleModel;