const vehicleBrand = [
    {
        id:"1",
        vehicleBrand:"Volkswagen"
    },
    {
        id:"2",
        vehicleBrand:"VolBMWkswagen"
    },
    {
        id:"3",
        vehicleBrand:"Audi"
    },
    {
        id:"4",
        vehicleBrand:"Ford"
    },
    {
        id:"5",
        vehicleBrand:"Opel"
    },
    {
        id:"6",
        vehicleBrand:"Toyota"
    },
    {
        id:"7",
        vehicleBrand:"Renault"
    },
    {
        id:"8",
        vehicleBrand:"Skoda"
    },
    {
        id:"9",
        vehicleBrand:"Peugeot"
    },
]

export default vehicleBrand;